# Generated by Django 6.0.5 on 2026-05-25 16:59

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('ideal_durations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Weekend', 'Weekend'), ('Short trip', 'Short trip'), ('One week', 'One week'), ('Long trip', 'Long trip')], max_length=50), blank=True, default=list)),
                ('budget_level', models.CharField(choices=[('Budget', 'Budget'), ('Mid-range', 'Mid-range'), ('Luxury', 'Luxury')], max_length=20)),
                ('culture', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('beaches', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nightlife', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cuisine', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='TransportOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_point', models.CharField(max_length=200)),
                ('arrival_point', models.CharField(max_length=200)),
                ('transport_type', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus')], max_length=20)),
                ('carrier_name', models.CharField(max_length=200)),
                ('route_number', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Culture', 'Culture'), ('Nature', 'Nature'), ('Beaches', 'Beaches'), ('Nightlife', 'Nightlife'), ('Cuisine', 'Cuisine')], max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='catalog.city')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='catalog.city')),
            ],
        ),
    ]
