# Generated by Django 6.0.5 on 2026-05-25 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='adventure',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='seclusion',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='urban',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='wellness',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Culture', 'Culture'), ('Adventure', 'Adventure'), ('Nature', 'Nature'), ('Beaches', 'Beaches'), ('Nightlife', 'Nightlife'), ('Cuisine', 'Cuisine'), ('Wellness', 'Wellness'), ('Urban', 'Urban'), ('Seclusion', 'Seclusion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='beaches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='cuisine',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='culture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='ideal_durations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Day trip', 'Day trip'), ('Weekend', 'Weekend'), ('Short trip', 'Short trip'), ('One week', 'One week'), ('Long trip', 'Long trip')], max_length=50), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='city',
            name='nature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='nightlife',
            field=models.IntegerField(),
        ),
    ]
