# Generated by Django 6.0.5 on 2026-06-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_city_adventure_city_seclusion_city_urban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
