# Generated by Django 6.0.5 on 2026-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_city_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('universal', models.CharField(blank=True, default='', max_length=20)),
                ('police', models.CharField(blank=True, default='', max_length=20)),
                ('ambulance', models.CharField(blank=True, default='', max_length=20)),
                ('fire', models.CharField(blank=True, default='', max_length=20)),
                ('tourist_police', models.CharField(blank=True, default='', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['country_name'],
            },
        ),
    ]
