# Generated by Django 6.0.5 on 2026-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationbooking',
            name='accommodation_details_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transportbooking',
            name='transport_details_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
