# Generated by Django 6.0.5 on 2026-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_accommodationbooking_accommodation_details_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripactivity',
            name='activity_details_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
