# Generated by Django 6.0.5 on 2026-06-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tripactivity_activity_details_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripactivity',
            name='activity_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
